# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


matrix:
  include:
    - r: release
      env: R_CODECOV=true
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      after_success:
        - Rscript -e 'covr::codecov()'

